SECTOR_STORIES = {
    1: {
        'title':    "SECTOR 1 — THE OUTER BELT",
        'subtitle': "Operation: First Contact",
        'lines': [
            "YEAR 2187. An unknown fleet has entered the outer asteroid belt.",
            "Initial scans confirm hostile intent. They are scanning our colonies.",
            "Command has authorized a strike force. You are the tip of the spear.",
            "Eliminate the Vanguard squadron and their command ship.",
            "Good luck, pilot. Earth is counting on you.",
        ],
        'boss_name': "VANGUARD",
        'boss_desc': "The enemy's advance warship. Fast and well-armed.",
    },
    2: {
        'title':    "SECTOR 2 — THE PHANTOM NEBULA",
        'subtitle': "Operation: Dark Matter",
        'lines': [
            "Vanguard is destroyed. But they sent a distress signal before falling.",
            "Deeper fleets are mobilizing. The Phantom Nebula is thick with enemies.",
            "Their new fighters have stealth plating — watch for phase-shifts.",
            "Intel suggests a cloaked command vessel is coordinating the attack.",
            "Find it. Destroy it. Leave nothing.",
        ],
        'boss_name': "PHANTOM",
        'boss_desc': "A ghost ship that teleports and fires from the shadows.",
    },
    3: {
        'title':    "SECTOR 3 — THE IRON CORRIDOR",
        'subtitle': "Operation: Iron Wall",
        'lines': [
            "The Phantom is gone. Their formations are collapsing.",
            "Command has intercepted a terrifying signal — a Leviathan-class ship.",
            "These vessels are the size of a moon. No pilot has ever faced one alone.",
            "You don't have a choice. The Iron Corridor is the last defensive line.",
            "Hold it. Or Earth burns.",
        ],
        'boss_name': "LEVIATHAN",
        'boss_desc': "A dreadnaught-class titan. Fires circular energy bursts.",
    },
    4: {
        'title':    "SECTOR 4 — THE SWARM ZONE",
        'subtitle': "Operation: Headhunter",
        'lines': [
            "The Leviathan has fallen. The enemy is in chaos.",
            "But chaos breeds desperation. The Swarm Zone is swarming.",
            "Our analysts have identified the hive-mind: NEMESIS.",
            "It controls the entire attack fleet. Destroy it, the swarm falls apart.",
            "This is the turning point. Make it count.",
        ],
        'boss_name': "NEMESIS",
        'boss_desc': "The alien hive-mind. Spreads volleys and spawns the swarm.",
    },
    5: {
        'title':    "SECTOR 5 — THE CORE",
        'subtitle': "Operation: Crownbreaker",
        'lines': [
            "NEMESIS is destroyed. The swarm has scattered.",
            "But the true enemy reveals itself at the heart of their fleet.",
            "THE OVERLORD. Their supreme commander. Ancient. Unstoppable.",
            "Every attack. Every loss. It was orchestrated from this command throne.",
            "Break the crown, pilot. Then follow whatever signal remains.",
        ],
        'boss_name': "OVERLORD",
        'boss_desc': "The fleet tyrant. Three phases. Maximum firepower.",
    },
    6: {
        'title':    "SECTOR 6 — THE NULL RIFT",
        'subtitle': "Operation: Ghost Knife",
        'lines': [
            "The Overlord is dead, but the fleet did not retreat.",
            "A signal pulled them through a tear in local space: the Null Rift.",
            "Ships vanish, reappear, and strike from impossible angles.",
            "A blade-shaped hunter is guarding the passage deeper in.",
            "Survive the rift. Destroy the VOID REAPER.",
        ],
        'boss_name': "VOID REAPER",
        'boss_desc': "A phase-blade ambusher. Fast movement and slashing volleys.",
    },
    7: {
        'title':    "SECTOR 7 — THE DYING SUN",
        'subtitle': "Operation: Solar Grave",
        'lines': [
            "Beyond the rift is a star being consumed from the inside.",
            "Its corona is crawling with warships feeding on the radiation.",
            "The source is alive: a parasite wrapped around the stellar core.",
            "If it finishes feeding, it will birth another invasion fleet.",
            "Enter the fire and kill the STAR DEVOURER.",
        ],
        'boss_name': "STAR DEVOURER",
        'boss_desc': "A solar parasite. Spiral bursts and burning beam volleys.",
    },
    8: {
        'title':    "SECTOR 8 — OBLIVION GATE",
        'subtitle': "Operation: Last Light",
        'lines': [
            "The dying sun collapses into a gate older than human history.",
            "Every enemy signal converges there. Every commander answered to it.",
            "At the center waits the machine intelligence: OBLIVION CORE.",
            "It does not conquer worlds. It erases them from memory.",
            "This is the last fight. No retreat. No second wave.",
        ],
        'boss_name': "OBLIVION CORE",
        'boss_desc': "The final ancient machine. Four phases of heavy fire.",
    },
    9: {
        'title':    "SECTOR 9 — THE HALO FORGE",
        'subtitle': "Operation: Broken Wings",
        'lines': [
            "The Oblivion Core was only one guardian in a chain of war engines.",
            "Past the gate, a forge world builds armored ships around a dead moon.",
            "New interceptor wings are faster than anything command has tracked.",
            "At the forge center waits a radiant execution vessel: IRON SERAPH.",
            "Clip its wings and shut the forge down.",
        ],
        'boss_name': "IRON SERAPH",
        'boss_desc': "A plated angel-warship. Rotating volleys and heavy phase fire.",
    },
    10: {
        'title':    "SECTOR 10 — THE SPORE SEA",
        'subtitle': "Operation: Containment",
        'lines': [
            "The forge coordinates point to a living cloud of infected wreckage.",
            "Alien spores are growing ships from broken hulls and dead machines.",
            "Bulwark-class defenders are shielding the infection from bombardment.",
            "The colony mind is birthing new fleets under the PLAGUE MOTHER.",
            "Burn the nest before it reaches human space.",
        ],
        'boss_name': "PLAGUE MOTHER",
        'boss_desc': "A hive carrier. Dense green spreads and shielded pressure.",
    },
    11: {
        'title':    "SECTOR 11 — FRACTURE DEPTHS",
        'subtitle': "Operation: Deep Cut",
        'lines': [
            "The Spore Sea breaks apart, revealing a gravity trench underneath.",
            "Wraith ships move through the fracture like ghosts in dark water.",
            "Sensor echoes show a colossal hull folding between dimensions.",
            "The RIFT COLOSSUS is opening a path for something even older.",
            "Enter the fracture and collapse it from within.",
        ],
        'boss_name': "RIFT COLOSSUS",
        'boss_desc': "A dimensional titan. Teleports and attacks from broken space.",
    },
    12: {
        'title':    "SECTOR 12 — THE RED TRIBUNAL",
        'subtitle': "Operation: Sentencing",
        'lines': [
            "The fracture leads to a fortress where enemy commanders are judged.",
            "Dreadnought escorts hold formation around a crimson command court.",
            "Every failed warlord has been recycled into its weapon systems.",
            "The CRIMSON JUDICATOR has sentenced Earth to extinction.",
            "Reject the verdict with everything you have.",
        ],
        'boss_name': "CRIMSON JUDICATOR",
        'boss_desc': "A brutal tribunal ship. Slashing patterns and savage phases.",
    },
    13: {
        'title':    "SECTOR 13 — ETERNITY ENGINE",
        'subtitle': "Operation: Forever Ends",
        'lines': [
            "Behind the tribunal is the machine that keeps the invasion reborn.",
            "It folds time around destroyed fleets and sends them back to war.",
            "Every victory will be undone unless the loop is shattered here.",
            "The ETERNITY ENGINE is awake, armed, and waiting.",
            "End the cycle. Make this war mortal.",
        ],
        'boss_name': "ETERNITY ENGINE",
        'boss_desc': "A time-forge superweapon. Five phases of final pressure.",
    },
}

WIN_TEXT = [
    "THE ETERNITY ENGINE HAS FALLEN.",
    "",
    "The time-loop shatters, and every resurrected invasion collapses at once.",
    "Earth receives your transmission: 'Mission complete.'",
    "",
    "Billions of lives, and every future they might build, are saved by one pilot.",
    "Your name will be written in the stars.",
    "",
    "HUMANITY ENDURES",
]
